### ISSUE TITLE
Nieprawidłowe wyświetlanie zdjeć w zakładce story

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#258]
Na dole pod osią czasu zdjęcia nie wyświetlają się zgodnie z projektem (poniżej): https://brightinventions.pl/about-us/story/

<img width="549" alt="Screenshot 2021-04-21 at 10 53 04" src="https://user-images.githubusercontent.com/82568642/115528193-1c615d80-a292-11eb-938f-6b8bfda31ab0.png">

**Comment by miensol** [comment]
@izabelapawlik Czy możesz wskazać dokładnie o jaki fragment chodzi?

 Nie twierdze, że jest idealnie ale wg. mnie dość [podobnie do Twojego zrzutu](https://brightinventions.pl/about-us/story):
 
![image](https://user-images.githubusercontent.com/357191/116814296-7b5b8800-ab58-11eb-9a4a-5c4203a17b71.png)

**Comment by izabelapawlik** [comment]
@miensol problem występuje na our story, ale ze slashem na końcu urla: https://brightinventions.pl/about-us/story/

![Screenshot 2021-05-04 at 08 34 36](https://user-images.githubusercontent.com/82568642/116967926-ae665e80-acb3-11eb-8eeb-6d7bb4abd73b.png)

**Comment by izabelapawlik** [comment]
będziemy robić redesign
