### ISSUE TITLE
Zmiany na blogu

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#260]
1. Dodanie lupki (możliwości szukania tekstów).
2. Dodanie kategorii i opcji klikania w kategorie.
3. Weryfikacja, czy teksty posiadają odpowiednią hierarchię nagłówków. (Iza)
4. Dodanie banerów pod klienta po prawej stronie tekstu, otagowanie ich. 5. Ewentualne rozróżnienie na tekts EB a tekst b2b, ale to raczej będzie trudne.
5. W przyszłości skracanie ulri w nowych tekstach, aby unikać takich adresów: https://brightinventions.pl/blog/which-hat-should-i-wear-today-how-to-make-your-meetings-and-brainstorming-sessions-more-effective (Iza)
6. Linki zewnętrzne w tekstach powinny być nofollow. Możemy to ogarnąć wtyczką?
7. Sprawdzenie, czy na blogu nie mamy broken links (pewnie kwestia wtyczki w gatsby?).

**Comment by miensol** [comment]
@izabelapawlik Wydaje mi się, że te pod punkty warto rozbić na osobne issues.

**Comment by izabelapawlik** [comment]
ok, porozdzielam to
