### ISSUE TITLE
Problem z sitemapą

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#275]
Zgodnie z komunikatem Google Search Console status sitemapy jest "Couldn't fetch". 
Choć była uploadowana, jest nieodstępna: https://brightinventions.pl/sitemap.xml

Wymagana naprawa :)

**Comment by miensol** [comment]
@izabelapawlik zweryfikuj proszę czy działa.

**Comment by izabelapawlik** [comment]
Niestety nie widzę poprawy. Sitemapa dalej niedostępna: https://brightinventions.pl/sitemap.xml 
W GSC komunikat bez zmian.

**Comment by miensol** [comment]
Zaktualizowałem wpis w google search console na https://brightinventions.pl/sitemap-index.xml 
@izabelapawlik sprawdź prosze czy teraz jest ok.

**Comment by izabelapawlik** [comment]
Sitemapa odczytana, w GSC stan sukces.
