### ISSUE TITLE
Self-referral w GA

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#276]
Zgodnie z GA w źródłach wejść na brightinventions.pl jest nasza strona. Nie wiem, jaka jest przyczyna. GA zbiera te referrale od marca 2021. Zaburza nam to statystyki. Prośba o pomoc w znalezieniu przyczyny i naprawienia tego.

Info o Googla: https://support.google.com/analytics/answer/6350128?hl=en

**Comment by miensol** [comment]
@izabelapawlik czy temat jest nadal aktualny?

**Comment by izabelapawlik** [comment]
@miensol analizuję to, dam znać.
