### ISSUE TITLE
Blog: wykrywanie broken links

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#288]
Zainstalowanie wtyczki na bloga, która poinformuje o broken links. Możliwość korzystania z niej przez marketing.

**Comment by miensol** [comment]
@izabelapawlik co to są broken links? 

Czy masz na myśli informację, że ktoś wszedł na jakiś adres URL ale nie było pod nim żadnej strony?

**Comment by izabelapawlik** [comment]
Tak, przez lata na blogu pojawiło się bardzo dużo linków w artykułach i jest duża szansa, że część z nich już nie jest dostępna. Gdy google bot crawluje takie artykuły, to "odbiera" to negatywnie, bo kierujemy usera donikąd. Z racji iż artykułów jest setki, trudno jest to wyłapać. Ja kilka zepsutych linków znalazłam przypadkiem i poprawiłam/usunęłam je. Wordpress ma wtyczkę, która je znajduje, zbiera w jednym miejscu i możesz szybko je usunąć. Podejrzewam, że Gatsby też musi coś takiego oferować.

**Comment by miensol** [comment]
Czy e-mail, który jest teraz wysyłany jest wystarczy?

**Comment by izabelapawlik** [comment]
Mi bardziej chodzi o linki zewnętrzne, które my dodajemy tworząc treści. Np. jak ktoś w tekście na blogu zalinkował do zewnętrznej strony 3 lata temu i link już jest nieaktywny. Przykład: ostatnio znalazłam w polityce prywatności link do strony Mozilli, który już nigdzie nie kierował. Tutaj to poprawiłam: https://github.com/bright/new-www/actions/runs/986492396

**Comment by miensol** [comment]
Ok 👌 Rozumiem. Przeszkadza nam to w SEO?

pt., 2 lip 2021, 10:44 użytkownik Izabela ***@***.***>
napisał:

**Comment by izabelapawlik** [comment]
Tak, dla bota to znak, że nie dbamy o experience użytkownika, który może nadziać się na takie linki. A czy ma to duże znaczenie? Tego nigdy do końca się nie dowiemy. :)
