### ISSUE TITLE
Upload zdjęcia

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#290]
Gdy publikujesz zdjęcie przez content managera, dodaje do ścieżki static i trzeba to potem usuwać w kodzie, bo inaczej, zdjęcie się nie ładuje na stronie. Nie jest to mega pilny bug, bardziej upierdliwy ;)

**Comment by miensol** [comment]
Gatsby najlepiej dziala z relatywnymi sciezkami. Najnowszy netlifycms wspiera relatywne sciezki. Najlepiej bedzie sprobowac wlaczyc te relatywne ciezki w configu netlify cms.

**Comment by miensol** [comment]
@izabelapawlik wg. mnie powinno już działać.

https://user-images.githubusercontent.com/357191/122514171-cf88d180-d00b-11eb-8027-a9ab8ba9aa06.mp4
