### ISSUE TITLE
Bio autora bloga

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#292]
Strona z autorem tekstu na blogu nie wyświetla się poprawnie: https://www.screencast.com/t/uwMCyg4P

Powinna wyświetlać się w ten sposób:

<img width="700" alt="Screenshot 2021-05-12 at 10 21 08" src="https://user-images.githubusercontent.com/82568642/117942869-d1c08780-b30b-11eb-9fdf-f8735dd98649.png">

**Comment by miensol** [comment]
@izabelapawlik sprawdź proszę teraz 🙏

**Comment by miensol** [comment]
Ok nadal nie działa. Tzn lokalnie działa, dopiero po wrzuceniu na _server_ nie. 
Tutaj jest jakiś wątek, który może być powiązany https://github.com/gatsbyjs/gatsby/discussions/27889

**Comment by izabelapawlik** [comment]
Działa :)

**Comment by izabelapawlik** [comment]
@miensol Racja, to dalej nie działa. Po odświeżeniu bio, jest problem: https://www.screencast.com/t/pq7NnQM8

To jest taka sama sytuacja, opisana w innym issues: https://github.com/bright/new-www/issues/277

**Comment by izabelapawlik** [comment]
@miensol hej, możemy wrócić do tego tematu? :)

**Comment by miensol** [comment]
@izabelapawlik wg mnie jest poprawione. Otwórz ponownie jeśli coś nie działa 🙏
