### ISSUE TITLE
Poprawienie link preview bloga na Facebooku

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#294]
Do uzupełnienia properties. Celem naprawienie wyświetlania grafiki.

![Screenshot 2021-05-05 at 08 55 04](https://user-images.githubusercontent.com/82568642/117106376-0cf90e80-ad80-11eb-8b20-d8f2758ed7dd.png)

Ponadto, czy podczas sherowania konkretnego wpisu mogłoby zaciągać grafikę z tego wpisu, a nie logo?

![Screenshot 2021-05-05 at 08 57 29](https://user-images.githubusercontent.com/82568642/117106360-05d20080-ad80-11eb-81ab-75e7230ea2a9.png)

**Comment by izabelapawlik** [comment]
@miensol Problemem są także pega title i description. Zamiast zaciągać dane z konkretnego wpisu, zaciąga ogólne teksty, zapewne z homepaga.

Jest tak:
![Screenshot 2021-05-17 at 14 01 17](https://user-images.githubusercontent.com/82568642/118485300-8a296980-b718-11eb-8cb3-a365f0e14ad7.png)


Powinno być tak (to jest preview z Googla, ale chodzi o to, że zaciąga właściwe teksty):

![Screenshot 2021-05-17 at 14 03 15](https://user-images.githubusercontent.com/82568642/118485422-b513bd80-b718-11eb-8ee6-dbfceb200937.png)

**Comment by miensol** [comment]
@izabelapawlik jaki obrazek powiniśmy ustawić w share w przypadku stron innych niż blog post?

**Comment by miensol** [comment]
@izabelapawlik Preview powinno się już wyświetlać lepiej.

**Comment by izabelapawlik** [comment]
@miensol Jest lepiej. Dzięki! 

Jutro dam znać, jakie zdjęcie/grafikę damy na innych stronach niż blog.

**Comment by izabelapawlik** [comment]
Podsyłam obrazek, który powinien zaciągać się gdy, sherujemy na Facebooku link do naszej strony (ale nie bloga). Na blogu pojawia się grafika do danego wpisu.
Grafika zgodna ze specyfikacją: https://developers.facebook.com/docs/sharing/webmasters/images/

![FB_Graph_meta-tag](https://user-images.githubusercontent.com/82568642/118933234-3fdaff00-b949-11eb-8032-8b11dccf12a8.png)

**Comment by izabelapawlik** [comment]
Gotowe.
