### ISSUE TITLE
Insufficient HTTPS coverage

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#300]
Google Search Console informuje, że mamy: Insufficient HTTPS coverage on your site.

Czy moglibyśmy to zbadać i ewentualnie naprawić?

**Comment by miensol** [comment]
@izabelapawlik Dodaj proszę link z konkretną informacją, może screen, gdzie ta informacja się znalazła w Google Search Console 🙏

**Comment by izabelapawlik** [comment]
@miensol Trzeba wejść w Page Experience raport: https://search.google.com/search-console/page-experience


![Screenshot 2021-05-07 at 13 05 11](https://user-images.githubusercontent.com/82568642/117440925-fd6ef680-af34-11eb-9203-f74c1057bc65.png)

**Comment by izabelapawlik** [comment]
Zamykam temat na razie. Ponoć to bug w raporcie po stronie Googla: https://www.seroundtable.com/google-search-console-insufficient-https-coverage-on-your-site-bug-31388.html
