### ISSUE TITLE
Nieprawidłowe wyświetlanie case studies na homepage

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#307]
Mamy sporą przestrzeń pomiędzy mockupem, a resztą sekcji. 

<img width="716" alt="Screenshot 2021-05-12 at 11 36 03" src="https://user-images.githubusercontent.com/82568642/117953593-747e0380-b316-11eb-90d6-d0536011e0c4.png">

Design hompegae dla porównania i weryfikacji https://xd.adobe.com/view/a7f0913d-b9f7-4643-9ffc-d24356fcfad8-f2a3/screen/0ba3ce72-5331-4049-8664-671ce3a2d065/

**Comment by miensol** [comment]
@izabelapawlik I've pushed a change [d167233](https://github.com/bright/new-www/commit/d167233d3551951142ca2ba024d3dc0b8dbd0bd6). Once deployed please let me know if the UI looks acceptable.

**Comment by izabelapawlik** [comment]
Strzałeczka uciekła na środek i tekst jest trochę szerszy niż powinien być. Na mobilu tej części wgl nie ma, a powinna być.
<img width="740" alt="Screenshot 2021-05-14 at 08 18 37" src="https://user-images.githubusercontent.com/82568642/118231006-c2b61280-b48e-11eb-9a50-adc63dc9018c.png">

**Comment by miensol** [comment]
Na mobile nie ma karuzeli ale zawartość zdaje się jest.

**Comment by izabelapawlik** [comment]
Wstrzymuję temat.
