### ISSUE TITLE
Błędne tłumaczenie MD na HTML?

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#318]
W artykule na blogu nie wyświetla się poprawnie w dwóch miejscach sekwencja: STRING_TOO_LARGE, pomimo iż w kodzie wygląda to poprawnie.

Artykuł: https://brightinventions.pl/blog/string-too-large-in-android-resources/

**JAK WYGLĄDA:**

<img width="1195" alt="Screenshot 2021-05-24 at 10 40 13" src="https://user-images.githubusercontent.com/82568642/119320985-7469f600-bc7c-11eb-8e99-fe8b4e2fad73.png">

<img width="1320" alt="Screenshot 2021-05-24 at 10 40 19" src="https://user-images.githubusercontent.com/82568642/119321174-a2e7d100-bc7c-11eb-811e-09e3620ac774.png">

**JAK POWINNO WYGLĄDAĆ:** 

![image](https://user-images.githubusercontent.com/82568642/119320859-4f758300-bc7c-11eb-9eb1-4a0a9f42d19f.png)

**Comment by izabelapawlik** [comment]
Ciąg dalszy problemu ze znakiem _

Linki z tym znakiem też się źle wyświetlają na blogu:

![image (1)](https://user-images.githubusercontent.com/82568642/119609940-b324bb00-bdf8-11eb-965b-1793f37e1e8e.png)

Widać to u Andrzeja w blog poście (na końcu artykułu): https://brightinventions.pl/blog/migrating-away-from-bintray-jcenter-when-there-is-no-alternative-repository/

**Comment by miensol** [comment]
@izabelapawlik sprawdź proszę czy jet ok.

**Comment by izabelapawlik** [comment]
Jest ok.
