### ISSUE TITLE
Tagi do blog postów (nie można dodać dwóch wyrazów w jednym tagu)

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#452]
W content managerze nie można dodać do wpisu na blogu taga z dwoma wyrazami, np. software development. Wciskanie spacji nic nie daje.

**Comment by miensol** [comment]
Dodałem własną kontrolke do tagow
<img width="1534" alt="Screenshot 2021-07-27 at 16 33 58" src="https://user-images.githubusercontent.com/357191/127173159-cf465fba-ea02-4ed1-a049-f99b9506b6ec.png">
