### ISSUE TITLE
Setting up Facebook Pixel

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#467]
Podrzucam maila z instrukcją. Niestety podczas wklejania formatowanie usuwa spacje w kodzie. 

W razie czego dostałeś maila od Uli z instrukcją. Temat maila: Ula Stankiewicz Sent You Instructions on Setting up Facebook Pixel
---

The pixel base code tracks activity on your website, providing a baseline for measuring specific events. Copy the base code below and paste it between the header tags on every page of your website:

```
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window,document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
 fbq('init', '1135879026880954'); 
fbq('track', 'PageView');
</script>
<noscript>
 <img height="1" width="1" 
src="https://www.facebook.com/tr?id=1135879026880954&ev=PageView
&noscript=1"/>
</noscript>
<!-- End Facebook Pixel Code -->
```

**Comment by izabelapawlik** [comment]
Zamykam chwilowo, jeszcze muszę coś przygotować po swojej stronie (formalności).

**Comment by miensol** [comment]
@izabelapawlik otwórz ponownie jeśli cośnie działa 🙏
