### ISSUE TITLE
Rel=nofollow błędnie ustawiony również dla linków kierujących do naszej domeny

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#618]
Hej,
chyba znów wtyczka nawaliła. Widzę na przykładzie tekstu: https://brightinventions.pl/blog/how-to-develop-a-healthcare-app-startup-owner-perspective/

Linkuję tutaj do naszych stron i linki do nas mają nofollow i otwierają się w nowej zakładce. Ta specyfikacja powinna dotyczyć tylko linków do zewnętrznych/obcych domen.

**Comment by miensol** [comment]
Zeby wtyczka działała trzeba ścieżek zamiast pełnych URLi. Zmiast pisać

```
[some title](https://brightinventions.pl/blog/how-to-develop-a-healthcare-app-startup-owner-perspective/)
```

piszemy

```
[some title](/blog/how-to-develop-a-healthcare-app-startup-owner-perspective/)
```
