### ISSUE TITLE
Brak favicon, grafiki-strzałki nie ładują się

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#629]
1. Brak favicon na Chrome. Na Safari działa.
<img width="1298" alt="Screenshot 2021-08-02 at 15 23 45" src="https://user-images.githubusercontent.com/82568642/127868889-409a6b1d-2f93-45a1-9ec5-3e4264dcb6ea.png">

2. Grafika-strzałka nie wyświetla się w witrynie. Znajduje się m.in. na dole blog posta czy case study
<img width="1335" alt="Screenshot 2021-08-02 at 15 25 38" src="https://user-images.githubusercontent.com/82568642/127869067-573d2ad1-1a47-4200-bfaf-4179567e2e2d.png">

<img width="1295" alt="Screenshot 2021-08-02 at 15 25 29" src="https://user-images.githubusercontent.com/82568642/127869091-8337cc2e-dc63-45fa-bd7a-cc8b2a7b5484.png">

**Comment by miensol** [comment]
Favicony poprawione 
![image](https://user-images.githubusercontent.com/357191/127919524-20338d57-6136-43f9-9f94-178decfe8e71.png)

**Comment by izabelapawlik** [comment]
Strzałki i favicon ok. Dzięki!
