### ISSUE TITLE
Grafiki na stronie nie ładują się.

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#699]
Gdy wchodzimy na którą z naszych podstron grafiki czy logo na górze nie ładują się. Trzeba kliknąć refreash i wtedy się ładują. Prośba o zbadanie sprawy.

Przykłady:

![Screenshot 2021-08-11 at 13 50 02](https://user-images.githubusercontent.com/82568642/129702545-08ef09b1-ce12-4556-a9e5-46d94a9ab0f6.png)

<img width="1405" alt="Screenshot 2021-08-17 at 11 40 23" src="https://user-images.githubusercontent.com/82568642/129702833-4760b2b4-a8a0-48d4-bb68-f6c5f5a207e6.png">

**Comment by miensol** [comment]
Wygląda na to, że upgrade paczek pomógł.

**Comment by izabelapawlik** [comment]
Moim zdaniem problem dalej występuje. Wchodzę dziś na bloga, a tam:

![Screenshot 2021-09-06 at 11 50 35](https://user-images.githubusercontent.com/82568642/132197936-a082a144-b73c-4a9f-9f88-2e532412348b.png)

**Comment by miensol** [comment]
W tej chwili dziala
![image](https://user-images.githubusercontent.com/357191/132218208-3efad548-fccc-45b6-9ede-1163d4c302fb.png)

ale też mam wrażenie że nie zawsze tak jest 🤔

**Comment by izabelapawlik** [comment]
Na ten moment grafiki się łądują poprawnie.
