### ISSUE TITLE
Przekierowanie usuniętych ogłoszeń o pracę

### ISSUE THREAD

**Issue by izabelapawlik** [bright/new-www#807]
Hej, dodaję tutaj ten temat, żeby nam nie umknął.

Do przemyślenia, jak przekierowywać usunięte oferty pracy, np. url: /jobs/senior-NET-developer

Generalnie usunięcie powinno być ostatecznością. Sensownym rozwiązaniem jest redirect do career tego konkretnego ogłoszenia. Jednak podczas ostatniej próby przekierowało wszystkie ogłoszenia ze ścieżki jobs/

**Comment by miensol** [comment]
Na tą chwilę wypróbuję ręczne przekierowanie. W przyszłości możemy albo oznaczać ogłoszenia jako nieaktywne i dla nich budować przekierowania.

**Comment by miensol** [comment]
Przekierowanie z /jobs/senior-NET-developer na /career dziala

**Comment by izabelapawlik** [comment]
Super, działa. Jak miałoby wyglądać oznaczanie ogłoszeń jako nieaktywne? Trzeba by przygotowac na to feature?

**Comment by miensol** [comment]
Mniej więcej tak jak z blog postami. Oznaczenie polem active/inactive.
To jest raczej proste do zrobienia.

śr., 8 wrz 2021 o 14:17 Izabela ***@***.***> napisał(a):
